version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:5000 "app:create_app()" --reload

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A tasks.celery_tasks.celery worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
      - web
    volumes:
      - .:/app
